/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenampilgambar;

import java.awt.CardLayout;

/**
 *
 * @author ACER
 */
public class tampilGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form tampilGambarButton
     */
    public tampilGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glassbtn = new javax.swing.JButton();
        javabtn = new javax.swing.JButton();
        postbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        javalbl = new javax.swing.JLabel();
        postlbl = new javax.swing.JLabel();
        glasslbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        glassbtn.setText("GlassFish");
        glassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glassbtnActionPerformed(evt);
            }
        });

        javabtn.setText("JavaEE");
        javabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javabtnActionPerformed(evt);
            }
        });

        postbtn.setText("PostgreeSql");
        postbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postbtnActionPerformed(evt);
            }
        });

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        javalbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\WhatsApp Image 2022-01-18 at 09.44.12 (1).jpeg")); // NOI18N
        jPanel1.add(javalbl, "1");

        postlbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\WhatsApp Image 2022-01-18 at 09.44.13.jpeg")); // NOI18N
        jPanel1.add(postlbl, "2");

        glasslbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\WhatsApp Image 2022-01-18 at 09.44.12.jpeg")); // NOI18N
        jPanel1.add(glasslbl, "0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(glassbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(javabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(postbtn)
                        .addGap(46, 46, 46)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(glassbtn)
                    .addComponent(javabtn)
                    .addComponent(postbtn)
                    .addComponent(exitbtn))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void javabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javabtnActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (jPanel1.getLayout());
        cl.show(jPanel1, "1");
    }//GEN-LAST:event_javabtnActionPerformed

    private void glassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glassbtnActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (jPanel1.getLayout());
        cl.show(jPanel1, "0");
    }//GEN-LAST:event_glassbtnActionPerformed

    private void postbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postbtnActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (jPanel1.getLayout());
        cl.show(jPanel1, "2");
    }//GEN-LAST:event_postbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton glassbtn;
    private javax.swing.JLabel glasslbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton javabtn;
    private javax.swing.JLabel javalbl;
    private javax.swing.JButton postbtn;
    private javax.swing.JLabel postlbl;
    // End of variables declaration//GEN-END:variables
}
